# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: VariableStrings

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'

# - script: |
#     export AZURE_COSMOS_CONNECTION_STRING=$(COSMOS_CS)
#     export AZURE_COSMOS_DATABASE_NAME=$(COSMOS_DB)
#     export APPLICATIONINSIGHTS_CONNECTION_STRING=$(APP_INSIGHTS_CS)
#     export APPLICATIONINSIGHTS_ROLE_NAME=$(APP_INSIGHTS_ROLE_NAME)
#     cd src/api
#     npm ci && npm test
#   displayName: Test API

- script: |
    cd src/web
    npm ci && npm audit fix && npm run build
  displayName: Build Web